var nome = window.prompt('Qual é seu nome?')
var idade = window.prompt('qual sua idade?')
var cidade = window.prompt('qual sua cidade?')
var sobrenome = window.prompt('qual sua sobrenome?')
document.write(`<h1>Suas informaçoes:</h1></br>`)
document.write(`<main><h2>Olá, <strong>${nome}</strong>!</h2></br>`)
document.write(`<p>NOME: ${nome}</p></br>`)
document.write(`<p>IDADE: ${idade} anos</p></br>`)
document.write(`<p>CIDADE: ${cidade}</p></br>`)
document.write(`<p>SOBRENOME: ${sobrenome}</p></br>`)
document.write(`<p><i>seu nome tem ${nome.length} letras.</p></i></main></br>`)